title: Amplify ✨
baseURL: 'https://bigspring.netlify.app/'
theme: ''
languageCode: ''
googleAnalytics: ''
enableRobotsTXT: true

markup:
  tableOfContents:
    endLevel: 6
    ordered: false
    startLevel: 4