baseURL = "https://bigspring.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Webify"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer_left]]
URL = "#"
name = "About Us"
[[menu.footer_left]]
URL = "#"
name = "Quick Start"
[[menu.footer_left]]
URL = "pricing"
name = "Pricing"
[[menu.footer_middle]]
URL = "pricing"
name = "Pricing"
[[menu.footer_middle]]
URL = "#"
name = "Platform"
[[menu.footer_middle]]
URL = "#"
name = "Features"
[[menu.footer_right]]
URL = "privacy-policy"
name = "Privacy Policy"
[[menu.footer_right]]
URL = "terms-conditions"
name = "Terms & Conditions"
[[menu.footer_right]]
URL = "faq"
name = "FAQ"
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 1
[[menu.main]]
URL = "pricing"
name = "Pricing"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "faq"
name = "FAQ"
weight = 4
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "© [<b>Avadhoot Dandekar</b>](https://www.avadhoot.me/) Designed By [Themefisher](https://themefisher.com/) Developed By [Gethugothemes](https://gethugothemes.com/) ✨ Proudly deployed on [<b>Netlify</b>](https://www.netlify.com/)"
description = "We are a web design and digital marketing agency."
footer_content = "We are a web design and digital marketing agency. We help amplify your digital footprint in the digital space. Let’s webify!!"
footer_menu_left = "Company"
footer_menu_middle = "Services"
footer_menu_right = "Support"
logo = "images/logo.png"
logo_width = "200px"
[params.navigation_button]
enable = true
label = "Get Started"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "ti-youtube"
link = "https://www.youtube.com/c/AvadhootDandekar"
title = "YouTube"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/avadhoot.me/"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/AvadhootMe"
title = "twitter"
[[params.social]]
icon = "ti-github"
link = "https://github.com/betterify"
title = "GitHub"
[[params.social]]
icon = "ti-linkedin"
link = "https://in.linkedin.com/in/avadhootdandekar2010"
title = "linkedin"
